# Generated by Django 3.2.5 on 2021-07-17 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0002_auto_20210717_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre de producto ')),
                ('plano', models.FileField(default='doc.pdf', upload_to='productos/plano/%c/pdf', verbose_name='PDF Plano o Ficha Tecnica')),
                ('expediente_diseño', models.FileField(default='doc.pdf', upload_to='productos/expediente_diseño/%c/pdf', verbose_name='PDF Expediente diseño')),
                ('plano_molde', models.FileField(default='doc.pdf', upload_to='productos/plano_molde/%c/pdf', verbose_name='PDF Plano de molde')),
                ('Costo_Producción', models.IntegerField(verbose_name='Costo produción')),
                ('Business_Products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
