# Generated by Django 3.2.5 on 2021-07-23 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210723_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproducts',
            old_name='expediente_diseño',
            new_name='expediente_diseno',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='expediente_diseño',
            new_name='expediente_diseno',
        ),
    ]
