# Generated by Django 3.2.5 on 2021-07-23 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210723_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducts',
            name='expediente_diseno',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Expediente diseño'),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='plano',
            field=models.TextField(blank=True, default='doc.pdf', max_length=100, null=True, verbose_name='PDF Plano o Ficha Tecnica'),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='plano_molde',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='PDF Plano de molde'),
        ),
        migrations.AlterField(
            model_name='products',
            name='expediente_diseno',
            field=models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='PDF Expediente diseño'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plano',
            field=models.FileField(blank=True, default='doc.pdf', null=True, upload_to='productos/', verbose_name='PDF Plano o Ficha Tecnica'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plano_molde',
            field=models.FileField(blank=True, null=True, upload_to='productos/', verbose_name='PDF Plano de molde'),
        ),
    ]
