# Generated by Django 3.2.5 on 2021-07-23 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210723_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='expediente_diseno',
            field=models.FileField(blank=True, null=True, upload_to='productos/expediente_diseno/%c/pdf', verbose_name='PDF Expediente diseño'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plano',
            field=models.FileField(blank=True, default='doc.pdf', null=True, upload_to='productos/plano/%c/pdf', verbose_name='PDF Plano o Ficha Tecnica'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plano_molde',
            field=models.FileField(blank=True, null=True, upload_to='productos/plano_molde/%c/pdf', verbose_name='PDF Plano de molde'),
        ),
    ]
