# Generated by Django 3.2.5 on 2021-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210723_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproducts',
            name='expediente_diseno',
            field=models.TextField(blank=True, default='doc.pdf', max_length=100, null=True, verbose_name='PDF Expediente diseño'),
        ),
        migrations.AlterField(
            model_name='historicalproducts',
            name='plano_molde',
            field=models.TextField(blank=True, default='doc.pdf', max_length=100, null=True, verbose_name='PDF Plano de molde'),
        ),
        migrations.AlterField(
            model_name='products',
            name='expediente_diseno',
            field=models.FileField(blank=True, default='doc.pdf', null=True, upload_to='productos/expediente_diseno/%c/pdf', verbose_name='PDF Expediente diseño'),
        ),
        migrations.AlterField(
            model_name='products',
            name='plano_molde',
            field=models.FileField(blank=True, default='doc.pdf', null=True, upload_to='productos/plano_molde/%c/pdf', verbose_name='PDF Plano de molde'),
        ),
    ]
