# Generated by Django 3.2.5 on 2021-07-17 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalprojects',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Proyecto'},
        ),
        migrations.AlterModelOptions(
            name='historicalprojectsproduct',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Producto del proyecto'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='projectsproduct',
            options={'verbose_name': 'Producto del proyecto', 'verbose_name_plural': 'Productos del proyecto'},
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('Cantidad', models.IntegerField(verbose_name='Nro de productos')),
                ('date_final', models.DateField(auto_now=True, verbose_name='Fecha Final')),
                ('RatioProducción', models.IntegerField(verbose_name='Avanze de productos por dia')),
                ('NroMoldes', models.IntegerField(verbose_name='Nro Moldes')),
                ('Observacion', models.TextField(verbose_name='Observacciónes')),
                ('Projects_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectsproduct', verbose_name='')),
                ('attendant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
            ],
            options={
                'verbose_name': 'Órden de producción',
                'verbose_name_plural': 'Órdenes de producción',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProductionOrder',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('Cantidad', models.IntegerField(verbose_name='Nro de productos')),
                ('date_final', models.DateField(blank=True, editable=False, verbose_name='Fecha Final')),
                ('RatioProducción', models.IntegerField(verbose_name='Avanze de productos por dia')),
                ('NroMoldes', models.IntegerField(verbose_name='Nro Moldes')),
                ('Observacion', models.TextField(verbose_name='Observacciónes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Projects_Product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.projectsproduct', verbose_name='')),
                ('attendant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Órden de producción',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
