# Generated by Django 3.2.5 on 2021-07-17 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0003_auto_20210717_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinforcementSteel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('TipoVarilla', models.CharField(max_length=50, verbose_name='Tipo de varilla')),
                ('CantidadVarilla', models.IntegerField(verbose_name='Cantidad de varilla(m)')),
                ('Order_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.productionorder', verbose_name='Orden producción')),
            ],
            options={
                'verbose_name': 'Asignación de acero refuerzo',
                'verbose_name_plural': 'Asignaciónes de acero refuerzo',
            },
        ),
        migrations.CreateModel(
            name='QuadrilaDay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('NroOperarios', models.IntegerField(verbose_name='Nro de operarios')),
                ('NroAyudante', models.IntegerField(verbose_name='Nro de ayudantes')),
                ('Order_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.productionorder', verbose_name='Orden producción')),
            ],
            options={
                'verbose_name': 'Asignación de cuadrilla/jornada',
                'verbose_name_plural': 'Asignaciónes de cuadrilla/jornada',
            },
        ),
        migrations.CreateModel(
            name='HistoricalReinforcementSteel',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('TipoVarilla', models.CharField(max_length=50, verbose_name='Tipo de varilla')),
                ('CantidadVarilla', models.IntegerField(verbose_name='Cantidad de varilla(m)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Order_Product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.productionorder', verbose_name='Orden producción')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Asignación de acero refuerzo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQuadrilaDay',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('NroOperarios', models.IntegerField(verbose_name='Nro de operarios')),
                ('NroAyudante', models.IntegerField(verbose_name='Nro de ayudantes')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Order_Product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.productionorder', verbose_name='Orden producción')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Asignación de cuadrilla/jornada',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
