# Generated by Django 3.2.5 on 2021-07-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_historicalquadriladay_historicalreinforcementsteel_quadriladay_reinforcementsteel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproductionorder',
            name='date_final',
            field=models.DateField(verbose_name='Fecha Final'),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='date_final',
            field=models.DateField(verbose_name='Fecha Final'),
        ),
    ]
