# Generated by Django 3.2.5 on 2022-03-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210813_0122'),
        ('projects', '0007_auto_20210829_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectsproduct',
            name='Product_Projects',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.products', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='projectsproduct',
            name='Product_Projects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.products', verbose_name='Producto'),
        ),
    ]
