# Generated by Django 3.2.5 on 2021-07-17 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre '),
        ),
        migrations.AddField(
            model_name='historicalbusiness',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Nombre '),
        ),
        migrations.AlterField(
            model_name='business',
            name='DirecionFiscal',
            field=models.CharField(max_length=120, verbose_name='Direción fiscal'),
        ),
        migrations.AlterField(
            model_name='historicalbusiness',
            name='DirecionFiscal',
            field=models.CharField(max_length=120, verbose_name='Direción fiscal'),
        ),
    ]
