# Generated by Django 3.2.5 on 2021-07-17 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de insumo ')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca ')),
                ('description', models.TextField(verbose_name='Descripcion del insumo')),
                ('UnitOfMeasurement', models.CharField(choices=[('Bolsas', 'bolsas'), ('Unidad', 'Unid'), ('IBC ', 'IBC'), ('Glb', 'Glb'), ('Kilo gramos', 'Kg'), ('Gramos', 'g'), ('Baldes', 'baldes')], max_length=50, verbose_name='Unidad de medida')),
                ('Business_Supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='Insumo de..')),
                ('Vendors_Supplies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors', verbose_name='Insumo de..')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
    ]
