# Generated by Django 3.2.5 on 2021-07-17 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210717_0331'),
        ('vendors', '0001_initial'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='Business_Supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='Vendors_Supplies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendors', verbose_name='Proveedor'),
        ),
    ]
