# Generated by Django 3.2.5 on 2021-07-17 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210717_0331'),
        ('vendors', '0002_historicalvendors'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supplies', '0002_auto_20210717_0531'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSupplies',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de insumo ')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca ')),
                ('description', models.TextField(verbose_name='Descripcion del insumo')),
                ('UnitOfMeasurement', models.CharField(choices=[('Bolsas', 'bolsas'), ('Unidad', 'Unid'), ('IBC ', 'IBC'), ('Glb', 'Glb'), ('Kilo gramos', 'Kg'), ('Gramos', 'g'), ('Baldes', 'baldes')], max_length=50, verbose_name='Unidad de medida')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Business_Supplies', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business', verbose_name='Empresa')),
                ('Vendors_Supplies', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='vendors.vendors', verbose_name='Proveedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Insumo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
