# Generated by Django 3.2.5 on 2021-07-18 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20210717_0331'),
        ('employee', '0002_historicalemployee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Business_Employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='historicalemployee',
            name='Business_Employee',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='business.business', verbose_name='Empresa'),
        ),
    ]
