# Generated by Django 3.2.5 on 2021-07-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltareo',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Control Asistencia'},
        ),
        migrations.AlterModelOptions(
            name='tareo',
            options={'verbose_name': 'Control Asistencia', 'verbose_name_plural': 'Controles de asistencia'},
        ),
        migrations.AlterField(
            model_name='historicaltareo',
            name='HoursJob',
            field=models.TimeField(verbose_name='Horas trasncurridas'),
        ),
        migrations.AlterField(
            model_name='tareo',
            name='HoursJob',
            field=models.TimeField(verbose_name='Horas trasncurridas'),
        ),
    ]
