# Generated by Django 3.2.5 on 2021-07-18 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0002_auto_20210718_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endurancetest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('FechaVaciado', models.DateField(verbose_name='Fecha vaciado')),
                ('FechaRotura', models.DateField(verbose_name='Fecha rotura')),
                ('PromedioFc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Fc (KgF/cm2)')),
                ('Report_Materials', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.reports', verbose_name='Reporte')),
            ],
            options={
                'verbose_name': 'Ensayo de resistencia',
                'verbose_name_plural': 'Ensayos de resistencias',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEndurancetest',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('FechaVaciado', models.DateField(verbose_name='Fecha vaciado')),
                ('FechaRotura', models.DateField(verbose_name='Fecha rotura')),
                ('PromedioFc', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Promedio Fc (KgF/cm2)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Report_Materials', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.reports', verbose_name='Reporte')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Ensayo de resistencia',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAirForce',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('ForceCompressionKn', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fuerza de compresion (Kn)')),
                ('AirCompressionCm2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Area de compresion (cm2)')),
                ('ForceCompressionKgF', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fuerza de compresion (KgF)')),
                ('Endurance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resistencia (KgF/cm2)')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('AirForceEndurancetest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='reports.endurancetest', verbose_name='Ensayo de resistencia')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Fuerza y Area',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AirForce',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('ForceCompressionKn', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fuerza de compresion (Kn)')),
                ('AirCompressionCm2', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Area de compresion (cm2)')),
                ('ForceCompressionKgF', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Fuerza de compresion (KgF)')),
                ('Endurance', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resistencia (KgF/cm2)')),
                ('AirForceEndurancetest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.endurancetest', verbose_name='Ensayo de resistencia')),
            ],
            options={
                'verbose_name': 'Fuerza y Area',
                'verbose_name_plural': 'Fuerzas y Areas',
            },
        ),
    ]
